spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/camp-pdf-maker
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true